# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-pereis
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clean
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    # (this is just an example, not intended to be a production configuration)
