// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Cliente       string   `json:"cliente"`
	Vendedor      string   `json:"vendedor"`
	Produto       string   `json:"produto"`
	Quantidade    *int     `json:"quantidade,omitempty"`
	PrecoUnitario *float64 `json:"precoUnitario,omitempty"`
	StatusPedido  *string  `json:"statusPedido,omitempty"`
	DataEntrega   *string  `json:"dataEntrega,omitempty"`
}

type Order struct {
	PedidoID      string   `json:"pedidoID"`
	Cliente       *string  `json:"cliente,omitempty"`
	Vendedor      *string  `json:"vendedor,omitempty"`
	Produto       *string  `json:"produto,omitempty"`
	Quantidade    *int     `json:"quantidade,omitempty"`
	PrecoUnitario *float64 `json:"precoUnitario,omitempty"`
	PrecoTotal    *float64 `json:"precoTotal,omitempty"`
	StatusPedido  *string  `json:"statusPedido,omitempty"`
	DataEntrega   *string  `json:"dataEntrega,omitempty"`
}

type Query struct {
}
